### PR TITLE
Added support for flexible PTX ISA detection

### LINKED ISSUE #29: PTX JIT compilation failed (Ver. 0.6.0)
Hi @m4rs-mt,

this will return an PTX JIT compilation error on Linux but works on Windows.
> _kernelRGB888PlanarToBGR888xPacked = _accelerator.LoadAutoGroupedStreamKernel<Index, int, int, int, ArrayView<byte>, ArrayView<byte>>(RGB888PlanarToBGR888xPacked);

Kernel:
```
private static void RGB888PlanarToBGR888xPacked(Index pixelIndex, int width, int height, int bpp, ArrayView<byte> source, ArrayView<byte> destination)
        {
            var offset = width * height;
            var r = source[pixelIndex];
            var g = source[pixelIndex + offset];
            var b = source[pixelIndex + offset * 2];

            destination[pixelIndex * bpp] = b;
            destination[pixelIndex * bpp + 1] = g;
            destination[pixelIndex * bpp + 2] = r;
        }
```

Only in version 0.6.0. The same code works with 0.5.1.

### PR DESCRIPTION
**Pull request by MoFtZ**
hi @m4rs-mt, here are some changes to try to fix #29, #36 and #39.

This should give a nicer error message, prompting users to update their CUDA drivers.

Not sure if the flexible PTX ISA detection is the best approach - let me know what you think.

### CODE REVIEW

**Comment by m4rs-mt** [comment]
I like the idea of an automated PTX-ISA detection that is fully implemented by ILGPU 🥇
