### PR TITLE
Fixed inlining OpenCL constants on if statements and function arguments

### PR DESCRIPTION
**Pull request by MoFtZ**
Fixed regression from commit 0609ea8b0a7be3dae746992c6c1e5dcaad54662e

`ILGPU.Tests.OpenCL.CLArrayViews_Debug.ArrayViewGetSubVariableView` kernel compilation failed because it generated code like `if (var20)` - `var20` was a constant, and never declared.

`ILGPU.Tests.OpenCL.CLGroupOperations_Debug.GroupDivergentControlFlow` kernel compilation failed because it generated code like `atomic_fetch_add ((atomic_int*)var12, , 1);` - appending the constant added a second/invalid comma.

### CODE REVIEW

**Comment by m4rs-mt** [comment]
Nice one! I accidentally added this to the master branch instead of the new v0.8.1 branch 🔢
