### ISSUE TITLE
PTX JIT compilation failed (Ver. 0.6.0)

### ISSUE THREAD

**Issue by LTOctum** [m4rs-mt/ILGPU#29]
Hi @m4rs-mt,

this will return an PTX JIT compilation error on Linux but works on Windows.
> _kernelRGB888PlanarToBGR888xPacked = _accelerator.LoadAutoGroupedStreamKernel<Index, int, int, int, ArrayView<byte>, ArrayView<byte>>(RGB888PlanarToBGR888xPacked);

Kernel:
```
private static void RGB888PlanarToBGR888xPacked(Index pixelIndex, int width, int height, int bpp, ArrayView<byte> source, ArrayView<byte> destination)
        {
            var offset = width * height;
            var r = source[pixelIndex];
            var g = source[pixelIndex + offset];
            var b = source[pixelIndex + offset * 2];

            destination[pixelIndex * bpp] = b;
            destination[pixelIndex * bpp + 1] = g;
            destination[pixelIndex * bpp + 2] = r;
        }
```

Only in version 0.6.0. The same code works with 0.5.1.

**Comment by m4rs-mt** [comment]
@LTOctum We have updated the minimum PTX version in v0.6 to PTX ISA 6.4 to support new GeForce RTX cards (see #25).

Can you check if the minimum driver version of your Linux setup is >= r418?

**Comment by LTOctum** [comment]
@m4rs-mt Good point, my Linux Nvidia driver was still on 380.

Thanks for the hint!
